[project]
name = "gym-results"
version = "0.1.0"
description = "The results repository for MTEB Gym"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["mteb-gym"]

[dependency-groups]
dev = ["pytest>=8.3.4"]

[tool.uv.sources]
mteb-gym = { git = "https://github.com/embeddings-benchmark/MTEB-gym-v2" }
